// <auto-generated />
using System;
using Know_Your_Nation_Speedy.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Know_Your_Nation_Speedy.Migrations
{
    [DbContext(typeof(MyDbContext))]
    partial class MyDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.1-servicing-10028")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Know_Your_Nation_Speedy.Models.Animations", b =>
                {
                    b.Property<int>("AnimationsId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("CoverImageLocation");

                    b.Property<string>("Description");

                    b.Property<string>("FileLocation");

                    b.Property<string>("Name");

                    b.HasKey("AnimationsId");

                    b.ToTable("AnimationsEntries");
                });

            modelBuilder.Entity("Know_Your_Nation_Speedy.Models.AnimationsWatched", b =>
                {
                    b.Property<int>("UsersId");

                    b.Property<int>("AnimationsId");

                    b.Property<int>("Rating");

                    b.Property<bool>("WatchedStatus");

                    b.HasKey("UsersId", "AnimationsId");

                    b.HasIndex("AnimationsId");

                    b.ToTable("AnimationsWatchedEntries");
                });

            modelBuilder.Entity("Know_Your_Nation_Speedy.Models.Articles", b =>
                {
                    b.Property<int>("ArticlesId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("CoverImageLocation");

                    b.Property<string>("Description");

                    b.Property<string>("FileLocation");

                    b.Property<bool>("InRotation");

                    b.Property<string>("Name");

                    b.Property<string>("Nation");

                    b.HasKey("ArticlesId");

                    b.ToTable("ArticlesEntries");
                });

            modelBuilder.Entity("Know_Your_Nation_Speedy.Models.ArticlesRead", b =>
                {
                    b.Property<int>("UsersId");

                    b.Property<int>("ArticlesId");

                    b.Property<bool>("GivenStatus");

                    b.Property<int>("Rating");

                    b.Property<bool>("ReadStatus");

                    b.HasKey("UsersId", "ArticlesId");

                    b.HasIndex("ArticlesId");

                    b.ToTable("ArticlesReadEntries");
                });

            modelBuilder.Entity("Know_Your_Nation_Speedy.Models.Books", b =>
                {
                    b.Property<int>("BooksId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("CoverImageLocation");

                    b.Property<string>("Description");

                    b.Property<string>("FileLocation");

                    b.Property<string>("Name");

                    b.HasKey("BooksId");

                    b.ToTable("BooksEntries");
                });

            modelBuilder.Entity("Know_Your_Nation_Speedy.Models.BooksRead", b =>
                {
                    b.Property<int>("UsersId");

                    b.Property<int>("BooksId");

                    b.Property<int>("Rating");

                    b.Property<bool>("ReadStatus");

                    b.HasKey("UsersId", "BooksId");

                    b.HasIndex("BooksId");

                    b.ToTable("BooksReadEntries");
                });

            modelBuilder.Entity("Know_Your_Nation_Speedy.Models.Comics", b =>
                {
                    b.Property<int>("ComicsId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("CoverImageLocation");

                    b.Property<string>("Description");

                    b.Property<string>("FileLocation");

                    b.Property<string>("Name");

                    b.HasKey("ComicsId");

                    b.ToTable("ComicsEntries");
                });

            modelBuilder.Entity("Know_Your_Nation_Speedy.Models.ComicsRead", b =>
                {
                    b.Property<int>("UsersId");

                    b.Property<int>("ComicsId");

                    b.Property<int>("Rating");

                    b.Property<bool>("ReadStatus");

                    b.HasKey("UsersId", "ComicsId");

                    b.HasIndex("ComicsId");

                    b.ToTable("ComicsReadEntries");
                });

            modelBuilder.Entity("Know_Your_Nation_Speedy.Models.Donations", b =>
                {
                    b.Property<int>("DonationsId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<double>("AmountDonated");

                    b.Property<DateTime>("Date");

                    b.Property<string>("Organization");

                    b.Property<int?>("UsersId");

                    b.HasKey("DonationsId");

                    b.HasIndex("UsersId");

                    b.ToTable("DonationsEntries");
                });

            modelBuilder.Entity("Know_Your_Nation_Speedy.Models.Events", b =>
                {
                    b.Property<int>("EventsId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Address");

                    b.Property<string>("Description");

                    b.Property<string>("ProjectName");

                    b.Property<DateTime>("date");

                    b.HasKey("EventsId");

                    b.ToTable("EventsEntries");
                });

            modelBuilder.Entity("Know_Your_Nation_Speedy.Models.Orders", b =>
                {
                    b.Property<int>("OrdersId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("AddressToDeliever");

                    b.Property<DateTime>("DateOrdered");

                    b.Property<string>("TrackingNumber");

                    b.Property<int?>("UsersId");

                    b.HasKey("OrdersId");

                    b.HasIndex("UsersId");

                    b.ToTable("OrdersEntries");
                });

            modelBuilder.Entity("Know_Your_Nation_Speedy.Models.ProductOrders", b =>
                {
                    b.Property<int>("OrdersId");

                    b.Property<int>("ProductsId");

                    b.Property<int>("Quantity");

                    b.HasKey("OrdersId", "ProductsId");

                    b.HasIndex("ProductsId");

                    b.ToTable("ProductOrdersEntries");
                });

            modelBuilder.Entity("Know_Your_Nation_Speedy.Models.Products", b =>
                {
                    b.Property<int>("ProductsId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("CoverImageLocation");

                    b.Property<string>("Description");

                    b.Property<string>("Name");

                    b.Property<double>("Price");

                    b.Property<int>("QuantityOnHand");

                    b.Property<int>("Rating");

                    b.Property<string>("Type");

                    b.HasKey("ProductsId");

                    b.ToTable("ProductsEntries");
                });

            modelBuilder.Entity("Know_Your_Nation_Speedy.Models.UserEvents", b =>
                {
                    b.Property<int>("UsersId");

                    b.Property<int>("EventsId");

                    b.HasKey("UsersId", "EventsId");

                    b.HasIndex("EventsId");

                    b.ToTable("VolunteerEntries");
                });

            modelBuilder.Entity("Know_Your_Nation_Speedy.Models.Users", b =>
                {
                    b.Property<int>("UsersId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Email");

                    b.Property<string>("MembershipType");

                    b.Property<string>("Name");

                    b.Property<string>("Password");

                    b.Property<string>("PhoneNumber");

                    b.Property<string>("Surname");

                    b.HasKey("UsersId");

                    b.ToTable("UsersEntries");
                });

            modelBuilder.Entity("Know_Your_Nation_Speedy.Models.AnimationsWatched", b =>
                {
                    b.HasOne("Know_Your_Nation_Speedy.Models.Animations", "Animation")
                        .WithMany("AnimationWatched")
                        .HasForeignKey("AnimationsId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("Know_Your_Nation_Speedy.Models.Users", "User")
                        .WithMany("AnimationWatched")
                        .HasForeignKey("UsersId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Know_Your_Nation_Speedy.Models.ArticlesRead", b =>
                {
                    b.HasOne("Know_Your_Nation_Speedy.Models.Articles", "Article")
                        .WithMany("ArticleRead")
                        .HasForeignKey("ArticlesId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("Know_Your_Nation_Speedy.Models.Users", "User")
                        .WithMany("ArticleRead")
                        .HasForeignKey("UsersId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Know_Your_Nation_Speedy.Models.BooksRead", b =>
                {
                    b.HasOne("Know_Your_Nation_Speedy.Models.Books", "Book")
                        .WithMany("BookRead")
                        .HasForeignKey("BooksId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("Know_Your_Nation_Speedy.Models.Users", "User")
                        .WithMany("BookRead")
                        .HasForeignKey("UsersId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Know_Your_Nation_Speedy.Models.ComicsRead", b =>
                {
                    b.HasOne("Know_Your_Nation_Speedy.Models.Comics", "Comic")
                        .WithMany("ComicRead")
                        .HasForeignKey("ComicsId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("Know_Your_Nation_Speedy.Models.Users", "User")
                        .WithMany("ComicRead")
                        .HasForeignKey("UsersId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Know_Your_Nation_Speedy.Models.Donations", b =>
                {
                    b.HasOne("Know_Your_Nation_Speedy.Models.Users", "User")
                        .WithMany("Donation")
                        .HasForeignKey("UsersId");
                });

            modelBuilder.Entity("Know_Your_Nation_Speedy.Models.Orders", b =>
                {
                    b.HasOne("Know_Your_Nation_Speedy.Models.Users", "User")
                        .WithMany("Order")
                        .HasForeignKey("UsersId");
                });

            modelBuilder.Entity("Know_Your_Nation_Speedy.Models.ProductOrders", b =>
                {
                    b.HasOne("Know_Your_Nation_Speedy.Models.Orders", "Order")
                        .WithMany("ProductOrder")
                        .HasForeignKey("OrdersId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("Know_Your_Nation_Speedy.Models.Products", "Product")
                        .WithMany("ProductOrder")
                        .HasForeignKey("ProductsId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Know_Your_Nation_Speedy.Models.UserEvents", b =>
                {
                    b.HasOne("Know_Your_Nation_Speedy.Models.Events", "Event")
                        .WithMany("UserEvent")
                        .HasForeignKey("EventsId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("Know_Your_Nation_Speedy.Models.Users", "User")
                        .WithMany("UserEvent")
                        .HasForeignKey("UsersId")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
